#!/usr/bin/env bash



if [[ "$#" == 0 ]]; then
  if [[ $(tail -n 1 ~/.wm) == "false" ]]; then
    $($(head -n 1 ~/.wm))
  else
    sed -i '$ d' ~/.xinitrc
    echo "exec $(head -n 1 ~/.wm)" >> ~/.xinitrc
    startx
  fi
elif [[ "$#" == 1 ]]; then
  if [[ "$1" == "hypr" ]]; then
    sed -i "1s/.*/Hyprland/" ~/.wm
    sed -i "2s/.*/false/" ~/.wm
    launch
  elif [[ "$1" == "i3" ]]; then
    sed -i "1s/.*/i3/" ~/.wm
    sed -i "2s/.*/true/" ~/.wm
    launch
  elif [[ "$1" == "dwm" ]]; then
    sed -i "1s/.*/dwm/" ~/.wm
    sed -i "2s/.*/true/" ~/.wm
    launch
  elif [[ "$1" == "bspwm" ]]; then
    sed -i "1s/.*/bspwm/" ~/.wm
    sed -i "2s/.*/true/" ~/.wm
    launch
  fi
fi
