# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
  # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
  "zip",
  "unzip",
  "clang",
  "gcc",
  "llvm",
  "vim",
  "base-devel",
  "git",
  "firefox",
  "kitty",
  "fish",
  "eza",
  "yazi",
  "neomutt",
  "neovim",
  "bluez",
  "networkmanager",
  "bluez-utils",
  "ripgrep",
  "fd",
  "fzf",
  "jq",
  "flameshot",
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
  "com.discordapp.Discord",
]
