[manager]
ratio = [1, 3, 4]
show_hidden = true
sort_by = "natural"
sort_dir_first = true
linemode = "permissions"
show_symlink = true

[opener]
edit = [
  { run = 'nvim "$@"', block = true },
]
play = [
  { run = 'mpv "$@"', orphan = true, for = "unix" },
]
open = [
  { run = 'xdg-open "$@"', desc = "Open" },
]

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
]
append_previewers = [
  { name = "*", run = "hexyl"},
]
