imports = [
  "nvidia",
  "yubikey",
]

[managers.serv_now] 
items = [
  "gdm",
]

[managers.system]
items = [
  "gnome",
  "jetbrains-toolbox",
  "tea",
]

[managers.flatpak]
items = [
  "com.modrinth.ModrinthApp",
  "com.valvesoftware.Steam",
]
